language: python
python:
  - "3.6.2"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
script:
  - "pytest"
  - "coveralls run test_users.py"
  - "coveralls run test_recipes.py"
after_success: coveralls

  