language: python
python:
  - "3.6.2"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
script:
  - "pytest test_user.py"
  - "pytest test_recipe.py"
  - "coverage run test_user.py"
  - "coverage run test_recipe.py"

after_success: coveralls